"""initial schema

Revision ID: 47a44131a3fc
Revises: 
Create Date: 2026-06-22 11:26:03.917152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47a44131a3fc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('icps',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('criteria_json', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('icps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_icps_account_id'), ['account_id'], unique=False)

    op.create_table('signals',
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('source_ref', sa.String(length=500), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'dedupe_key', name='uq_signal_dedupe')
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signals_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_dedupe_key'), ['dedupe_key'], unique=False)

    op.create_table('campaigns',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('icp_id', sa.String(length=32), nullable=True),
    sa.Column('channel_sequence_json', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('daily_cap', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['icp_id'], ['icps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_account_id'), ['account_id'], unique=False)

    op.create_table('prospects',
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('headline', sa.String(length=400), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('linkedin_url', sa.String(length=400), nullable=True),
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.Column('origin_signal_id', sa.String(length=32), nullable=True),
    sa.Column('enrichment_status', sa.String(length=20), nullable=False),
    sa.Column('suppressed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['origin_signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'dedupe_key', name='uq_prospect_dedupe')
    )
    with op.batch_alter_table('prospects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prospects_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prospects_dedupe_key'), ['dedupe_key'], unique=False)

    op.create_table('enriched_contacts',
    sa.Column('prospect_id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('email_status', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('seniority', sa.String(length=60), nullable=True),
    sa.Column('company_domain', sa.String(length=200), nullable=True),
    sa.Column('company_size', sa.Integer(), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('provider', sa.String(length=60), nullable=True),
    sa.Column('provider_raw_json', sa.JSON(), nullable=True),
    sa.Column('enriched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prospect_id')
    )
    with op.batch_alter_table('enriched_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enriched_contacts_account_id'), ['account_id'], unique=False)

    op.create_table('scored_leads',
    sa.Column('prospect_id', sa.String(length=32), nullable=False),
    sa.Column('icp_id', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=2), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('matched_criteria_json', sa.JSON(), nullable=True),
    sa.Column('model_id', sa.String(length=60), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['icp_id'], ['icps.id'], ),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scored_leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scored_leads_account_id'), ['account_id'], unique=False)

    op.create_table('draft_messages',
    sa.Column('scored_lead_id', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('model_id', sa.String(length=60), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scored_lead_id'], ['scored_leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('draft_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_draft_messages_account_id'), ['account_id'], unique=False)

    op.create_table('approval_items',
    sa.Column('draft_message_id', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('reviewer_note', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['draft_message_id'], ['draft_messages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draft_message_id')
    )
    with op.batch_alter_table('approval_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_items_account_id'), ['account_id'], unique=False)

    op.create_table('outreach_logs',
    sa.Column('draft_message_id', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=True),
    sa.Column('provider_message_id', sa.String(length=200), nullable=True),
    sa.Column('event', sa.String(length=20), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['draft_message_id'], ['draft_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outreach_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outreach_logs_account_id'), ['account_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outreach_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outreach_logs_account_id'))

    op.drop_table('outreach_logs')
    with op.batch_alter_table('approval_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_items_account_id'))

    op.drop_table('approval_items')
    with op.batch_alter_table('draft_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_draft_messages_account_id'))

    op.drop_table('draft_messages')
    with op.batch_alter_table('scored_leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scored_leads_account_id'))

    op.drop_table('scored_leads')
    with op.batch_alter_table('enriched_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enriched_contacts_account_id'))

    op.drop_table('enriched_contacts')
    with op.batch_alter_table('prospects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prospects_dedupe_key'))
        batch_op.drop_index(batch_op.f('ix_prospects_account_id'))

    op.drop_table('prospects')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_account_id'))

    op.drop_table('campaigns')
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_dedupe_key'))
        batch_op.drop_index(batch_op.f('ix_signals_account_id'))

    op.drop_table('signals')
    with op.batch_alter_table('icps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_icps_account_id'))

    op.drop_table('icps')
    # ### end Alembic commands ###
